export const bookGenres = [
  "Narrativa",
  "Fantasia",
  "Ciencia ficcion",
  "Romance",
  "Misterio",
  "Terror",
  "Historia",
  "Manga y comic",
];

export const mockBooks = [
  {
    id: "atelier-3",
    title: "Atelier of Witch Hat 3",
    author: "Kamome Shirahama",
    description:
      "Coco sigue aprendiendo los secretos del dibujo magico en una historia delicada, contemplativa y visualmente hipnotica.",
    genre: ["Fantasia", "Manga y comic"],
    language: "es",
    pages: 192,
    format: "MOBI",
    rating: 4.8,
    readers: 12084,
    progress: 0.61,
    downloaded: true,
    favorite: true,
    tone: "Contemplativo",
    collection: "Mesa de estudio",
    coverPalette: ["#D9D0C2", "#6F8273", "#C4A04D"],
  },
  {
    id: "howl",
    title: "Howl's Moving Castle",
    author: "Diana Wynne Jones",
    description:
      "Fantasía brillante con humor, hogar en movimiento y personajes memorables.",
    genre: ["Fantasia", "Narrativa"],
    language: "es",
    pages: 320,
    format: "MOBI",
    rating: 4.7,
    readers: 8342,
    progress: 0.28,
    downloaded: true,
    favorite: true,
    tone: "Ludico",
    collection: "Mesa de estudio",
    coverPalette: ["#B8C5D6", "#6D6F84", "#8D6B2A"],
  },
  {
    id: "kiki",
    title: "Kiki's Delivery Service",
    author: "Eiko Kadono",
    description:
      "Una aventura suave sobre crecer, encontrar oficio y construir hogar.",
    genre: ["Fantasia", "Narrativa"],
    language: "es",
    pages: 224,
    format: "MOBI",
    rating: 4.5,
    readers: 6430,
    progress: 0,
    downloaded: false,
    favorite: false,
    tone: "Luminoso",
    collection: "Estante de luz",
    coverPalette: ["#F2D7A0", "#4B6B8A", "#B55F4A"],
  },
  {
    id: "momo",
    title: "Momo",
    author: "Michael Ende",
    description:
      "Una fabula sobre el tiempo, el cuidado y la escucha profunda.",
    genre: ["Fantasia", "Narrativa"],
    language: "es",
    pages: 288,
    format: "MOBI",
    rating: 4.6,
    readers: 7588,
    progress: 0.13,
    downloaded: true,
    favorite: false,
    tone: "Poetico",
    collection: "Mesa de estudio",
    coverPalette: ["#9AB2A8", "#C8C1D8", "#8D6B2A"],
  },
  {
    id: "earthsea",
    title: "A Wizard of Earthsea",
    author: "Ursula K. Le Guin",
    description:
      "Magia, nombre verdadero y formacion interior en un clasico absoluto.",
    genre: ["Fantasia", "Narrativa"],
    language: "en",
    pages: 240,
    format: "MOBI",
    rating: 4.9,
    readers: 15402,
    progress: 0,
    downloaded: false,
    favorite: false,
    tone: "Epico",
    collection: "Bosque y lluvia",
    coverPalette: ["#4A6C7A", "#D8CFBF", "#C4A04D"],
  },
  {
    id: "coraline",
    title: "Coraline",
    author: "Neil Gaiman",
    description:
      "Un cuento oscuro, preciso y encantador sobre curiosidad y valentia.",
    genre: ["Misterio", "Terror"],
    language: "es",
    pages: 176,
    format: "MOBI",
    rating: 4.4,
    readers: 9387,
    progress: 0,
    downloaded: false,
    favorite: false,
    tone: "Oscuro",
    collection: "Bosque y lluvia",
    coverPalette: ["#55607C", "#BBB1CC", "#D0B46A"],
  },
  {
    id: "spirited",
    title: "Spirited Away Film Comic",
    author: "Hayao Miyazaki",
    description:
      "Viaje visual por un mundo espiritual lleno de detalles y misterio amable.",
    genre: ["Manga y comic", "Fantasia"],
    language: "es",
    pages: 160,
    format: "MOBI",
    rating: 4.8,
    readers: 5120,
    progress: 0,
    downloaded: true,
    favorite: false,
    tone: "Onirico",
    collection: "Estante de luz",
    coverPalette: ["#7FAFC4", "#E5DABF", "#708274"],
  },
  {
    id: "little-prince",
    title: "El Principito",
    author: "Antoine de Saint-Exupery",
    description:
      "Un texto breve, simbolico y perfecto para una experiencia de lectura reposada.",
    genre: ["Narrativa", "Fantasia"],
    language: "es",
    pages: 128,
    format: "MOBI",
    rating: 4.7,
    readers: 20990,
    progress: 0.92,
    downloaded: true,
    favorite: true,
    tone: "Lirico",
    collection: "Rincon querido",
    coverPalette: ["#9FC6D5", "#F2E6C9", "#C4A04D"],
  },
];

export const readerPreview = [
  "El papel guardaba un murmullo tenue, como si la tinta recordara los dedos de cada lector que la habia rozado antes.",
  "Coco acerco el libro a la luz y el borde dorado devolvio un brillo acuatico, casi como un hechizo discreto que solo existe para quien se detiene.",
  "En ese instante entendio que un buen taller no abruma: orienta, acompana y deja respirar la imaginacion.",
];
